### ISSUE TITLE
need to read info block

### ISSUE THREAD

**Issue by ktarbet** [HydrologicEngineeringCenter/dss-file-spec#2]
FileHeader  (first section)
FileHash   long[8192]  for example

hashFunction('/testing/timeseries/Flow/01Jan1900/1Day/series0/') --> 
zhash; Table Hash:  5228,  Maximum Hash: 8192,  Bin Hash: -3117397283474765467

example fileHash[5228] has address to bin   -> 9372
bin.infoAddress --> info block (TO DO)

------ bin -----
bin address:9372
pathHash:-3117397283474765467
status: Good
numChars:48
size: 6
info address: 15773
data type: 100
sort sequence: 0
lastwrite: 1660313322483
julian start: 1
julian end: 3
pathname: /testing/timeseries/Flow/01Jan1900/1Day/series0/
next pathname hash: 8243121572436079663

**Comment by neemanejad** [comment]
There's two structs that hold info:

```
struct {
	   int kinfoFlag;
	   int kinfoStatus;
	   int kinfoPathnameLength;
	   int kinfoHash;
	   int kinfoTypeVersion;
	   int kinfoExpansion;
	   int kinfoLastWriteTime;
	   int kinfoProgram;
	   int kinfoFirstDate;
	   int kinfoLastDate;
	   int kinfoCreationTime;
	   int kinfoReserved1;
       int kinfoInternalHeadAddress;
	   int kinfoInternalHeadNumber;
	   int kinfoHeader2Address;
	   int kinfoHeader2Number;
	   int kinfoUserHeadAddress;
	   int kinfoUserHeadNumber;
	   int kinfoValues1Address;
	   int kinfoValues1Number;
	   int kinfoValues2Address;
	   int kinfoValues2Number;
	   int kinfoValues3Address;
	   int kinfoValues3Number;
	   int kinfoAllocatedSize;
	   int kinfoNumberData;
	   int kinfoLogicalNumber;
	   int kinfoAliasesBinAddress;
	   int kinfoReserved;
	   int kinfoPathname;
} zdssInfoKeys;
```
and 

```
struct {
	int kbinHash;
	int kbinStatus;
	int kbinPathLen;
	int kbinInfoAdd;
	int kbinTypeAndCatSort;
	int kbinLastWrite;
	int kbinDates;
	int kbinPath;
	int kbinSize;
} zdssBinKeys;
```
